version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
  covibot:
    depends_on:
      - dynamodb
    build:
      context: ./covibot
      dockerfile: Dockerfile
    volumes:
      - "~/.aws/:/root/.aws/:ro"
      - "./covibot/:/app/"
    environment:
      - DB_URL=http://dynamodb:8000
    image: covibot
    container_name: covibot
    ports:
      - "0.0.0.0:5000:5000"
